### ISSUE TITLE
Peggy can get away with false solution

### ISSUE THREAD

**Issue by dooglius** [Manishearth/sudoku-zkp#1]
(x-posted from my comment on Hacker News)

Suppose that in a puzzle there is only one 1 and one 9 that do not overlap in any way (row, column, or 3x3 square). Now, suppose that Peggy comes up with a false solution to the problem which sets both of these tiles to 9. Then, neither the 1 nor the 9 can be picked for the green squares, and so no test of Victor's can disprove Peggy's false solution.

This seems easily fixable too: rather than the whole green tiles thing, just allow Victor to query either a row/column/3x3 to prove the solution is a valid sudoku, or query the original filled in tiles, to show that the solution corresponds to the original problem.

I've come up with an example (look at the 1 and the 9) and verified this:
![screencapture-manishearth-github-io-sudoku-zkp-zkp-html-1470926941066](https://cloud.githubusercontent.com/assets/2808653/17592733/fd06e45e-5fa8-11e6-82d2-eecc7a733e77.png)

**Comment by Manishearth** [comment]
Good observation! I initially was going to go with having a preset option, but I didn't think it was necessary. Added. Will update post shortly.

**Comment by Manishearth** [comment]
Wait, that solution is totally wrong. Hold on.

**Comment by Manishearth** [comment]
Should be fixed now 😄 

Thanks!
